Matt-Eva/Encounter

client/package-lock.json, client/package.json, client/src/index.js, client/src/store.js, client/src/userAuth/Login.js
Redux has been installed and the store and global provider have been set up.
=> installed redux, set up store and provider

client/src/context/userState.js, client/src/index.js, db/migrate/20220103170111_remove_password_from_users.rb, db/migrate/20220103170145_add_password_digest_to_users.rb
Created our context folder.
Created a useContext file for user.
=> context folder added, userContext created

app/controllers/users_controller.rb, client/src/home/HomePage.js, client/src/userAuth/LogoutButton.js, client/src/userAuth/Signup.js
Implemented signup and logout functionality.
=> signup functionality implemented

client/src/HomePage.js, client/src/SearchBar.js, client/src/home/HomePage.js
Removed extraneous homepage and search files.
Imported resources into Homepage file.
Did some preliminary formatting.
=> some homepage layout changed

client/src/App.js, client/src/campaign/CampaignPage.js, client/src/encounter/EncounterCard.js
Setup up campaign splash page
Created encounter cards for encounters
=> Set up campaign page

app/controllers/campaigns_controller.rb, client/src/App.js, client/src/encounter/CreateEncounterPage.js
Added the end I accidentally deleted when resolving merge conflicts in campaign routes
=> fixed server routes, added create encounter page route to app

client/src/campaign/CampaignCard.js
Added route that allows you to view a campaign from the homepage using the "view" button on a campaign card.
=> route implemented

client/src/campaign/CampaignPage.js, client/src/context/selectedCampaignState.js, client/src/encounter/CreateEncounterPage.js, client/src/index.js
Created useContext hook for selected campaign.
=> added selected campaign context

app/controllers/campaigns_controller.rb, client/src/campaign/CampaignCard.js, client/src/campaign/CampaignPage.js
Can now delete campaigns from homepage using delete functionality on campaign card.
=> campaign delete functionality implemented

client/src/campaign/CampaignCard.js, client/src/campaign/CampaignPage.js, client/src/campaign/CreateCampaignForm.js, client/src/encounter/CreateEncounterPage.js, client/src/encounter/EncounterCard.js, client/src/home/HomePage.js
Set up new encounter form.
Created selected campaign context.
Have delete and create for encounter CRUD done.
Need to fix dynamic rendering of the encounter cards on campaign page then.
=> Set up encounter form (mostly works)

app/controllers/campaigns_controller.rb, client/src/App.js, client/src/campaign/CampaignCard.js, client/src/campaign/EditCampaignForm.js, client/src/campaign/EditCampaignPage.js, client/src/context/editCampaignState.js, client/src/home/HomePage.js, client/src/index.js
Created an EditCampaignPage component and EditCampaignForm component.
Implemented edit campaign functionality (PATCH).
=> implemented campaign edit functionality

client/src/campaign/CampaignCard.js
Needed get setSelectedCampaign from SelectedCampaignState using useContext.
=> added setSelectedCampaign from useContext

app/controllers/encs_controller.rb, client/src/campaign/CampaignCard.js, client/src/campaign/CampaignPage.js, client/src/context/encountersState.js, client/src/encounter/CreateEncounterPage.js, client/src/index.js, config/routes.rb
-Fixed code smell for encounters by creating a useContext hook.
-Fixed lack of image on create encounter form.
=> Create encounter page

client/src/App.js, client/src/campaign/CampaignCard.js, client/src/campaign/CreateCampaignPage.js, client/src/encounter/CreateEncounterPage.js, client/src/encounter/EncounterCard.js, client/src/home/HomePage.js, client/src/userAuth/Login.js, client/src/userAuth/Signup.js
Fixed some issues with initial app load.
Refactored due to fixes.
Set up route to view Encounter page.
=> View encounter page

app/models/enc.rb, app/serializers/enc_serializer.rb
=> forgot to commit from top level

app/controllers/encs_controller.rb, client/src/App.js, client/src/campaign/EditCampaignForm.js, client/src/campaign/EditCampaignPage.js, client/src/context/editEncounterState.js, client/src/encounter/EditEncounterForm.js, client/src/encounter/EditEncounterPage.js, client/src/encounter/EncounterCard.js, client/src/index.js
Created edit encounter page and form.
Created update route in enc controller.
Implemented full update functionality.
Reroute to campaign page after edit.
=> Edit encounter form

app/controllers/npcs_controller.rb, app/serializers/enc_serializer.rb, client/src/App.js, client/src/encounter/EncounterPage.js, client/src/npc/CreateEncounterNpcForm.js, client/src/npc/EncounterNpcPage.js, client/src/npc/NpcPage.js, config/routes.rb
Created npc form and npc page.
=> Create npc form

client/src/encounter/EncounterPage.js
-Fixed the conditional rendering of our NPC, Monster, Location, and Items
=> successfully debugged encounter page rendering

app/controllers/locations_controller.rb, client/src/App.js, client/src/encounter/EncounterPage.js, client/src/location/CreateEncounterLocationForm.js, client/src/location/EncounterLocationPage.js, config/routes.rb
-Created enc location form
-Front end conditonally rendering the locations.
=> created enc location form and have front end conditionally rendering

client/src/campaign/CampaignCard.js, client/src/campaign/CampaignDisplayContainer.js, client/src/home/HomePage.js
Implemented background image for homepage.
Started on some preliminary card styling.
Did some other homepage formatting.
=> homepage background image implemented

client/src/campaign/CampaignDisplayContainer.js, client/src/home/HomePage.js, client/src/home/SearchBar.js
set up search bar function for campaigns
=> Setup search bar

client/src/home/HomePage.js
=> created campaign filtration

client/src/campaign/CampaignDisplayContainer.js, client/src/campaign/CampaignPage.js, client/src/encounter/EncounterDisplayContainer.js, client/src/encounter/EncounterPage.js, client/src/home/Filter.js, client/src/home/HomePage.js
-Set up search bar on campaign page
-Abstracted filter component
-Set up filter on campaign page
=> Abstract filter

client/src/campaign/CampaignCard.js
You can now toggle the status for campaigns between active and archived.
=> change campaign status implemented

client/src/campaign/CampaignPage.js, client/src/encounter/EncounterCard.js, client/src/encounter/EncounterPage.js
Solved truncated background image problem.
Background image now covers full page upon initial load, even if there isn't any material on the page.
Use minHeight: 100vh to set image height.
=> formatted full-page background image

client/src/encounter/CreateEncounterPage.js, client/src/encounter/EncounterCard.js
Implemented toggle encounter status on encounter cards.
=> toggle encounter status implemented

client/src/encounter/EncounterPage.js
Can view and toggle between an encounter's npcs on an encounter page.
=> basic npc formatting implemented

client/src/encounter/EncounterPage.js
-Enc Npc display cleaned up a bit.
=> created semi-ok looking displays for Npcs

client/src/encounter/EncounterPage.js
-Created format for displayed enc monsters
-Changed format of names for enc npcs and monsters to h2's
=> Format enc monsters

client/src/campaign/CampaignCard.js, client/src/campaign/CampaignPage.js, client/src/encounter/EncounterCard.js, client/src/userAuth/LogoutButton.js
Changed button colors from blue to red.
=> button colors changed

client/src/encounter/EncounterPage.js
-Formatted encounter items display similarly to the design of NPC and Monsters
=> Formatted items display on encounters

client/src/campaign/CreateCampaignForm.js
Submitting new campaign on create campaign form now routes you back home.
=> create campaign from routes you home

client/src/encounter/EncounterPage.js
=> formatted encounters

client/src/encounter/EncounterPage.js
Finished stylizing the encounter page.
=> enc page looks good

client/src/campaign/EditCampaignForm.js, client/src/campaign/EditCampaignPage.js, client/src/encounter/CreateEncounterForm.js, client/src/encounter/CreateEncounterPage.js, client/src/home/HomePage.js, client/src/userAuth/LogoutButton.js
Made some formatting changes to createEncounterPage and Form
=> Edit campaign page formatting

client/src/campaign/CampaignPage.js, client/src/campaign/EditCampaignPage.js, client/src/encounter/CreateEncounterPage.js, client/src/encounter/EditEncounterForm.js, client/src/encounter/EditEncounterPage.js, client/src/encounter/EncounterPage.js
Made styling changes to editEncounterForm
Implemented other minor styling changes throughout app to promote consistency.
=> changed editEncounterForm styling and cleaned up other styling

client/src/userAuth/Login.js, client/src/userAuth/Signup.js
Minor style updates to login and signup pages.
=> updated login and signup page styles

client/src/App.js, client/src/encounter/EncounterPage.js, client/src/item/CreateEncounterItemForm.js, client/src/location/CreateEncounterLocationForm.js, client/src/monster/CreateEncounterMonsterForm.js, client/src/npc/CreateEncounterNpcForm.js, client/src/userAuth/Signup.js
-Retained selected encounter through create location/monster/items/npcs for encs.
=> Bombproof forms

client/src/App.js, client/src/campaign/CampaignCard.js, client/src/campaign/EditCampaignForm.js, client/src/campaign/EditCampaignPage.js
Upon refresh, edit campaign form still loads correct info.
=> bombproofed edit campaign form

client/src/campaign/CampaignCard.js, client/src/encounter/EditEncounterPage.js, client/src/encounter/EncounterCard.js, client/src/home/HomePage.js
-Formatted home page
-Formatted encounter cards
-Fixed edit encounter form background wiggle
-Refer to the background style/container className for styling.
=> Format home

client/src/encounter/CreateEncounterPage.js, client/src/item/EncounterItemPage.js, client/src/location/EncounterLocationPage.js, client/src/monster/EncounterMonsterPage.js, client/src/npc/EncounterNpcPage.js
Added consistent styling to all Encounter resource forms (item, location, monsters, npcs).
=> Format enc resources forms

client/src/App.js, client/src/campaign/CreateCampaignForm.js, client/src/campaign/EditCampaignForm.js, client/src/home/HomePage.js, client/src/home/Icon.js, client/src/userAuth/Login.js, client/src/userAuth/Signup.js
Used a conditional useEffect on homepage load to handle load problem.
=> Testing initial load routing
